name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  backend_deployment_pipeline:
    name: backend_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Install backend dependencies
        run: |
          cd server
          npm install

      - name: Lint backend
        run: |
          cd server
          npm run lint
    
      - name: Test backend
        run: |
          cd server
          npm run test
    
      - name: Build backend
        run: |
          cd server
          npm run tsc

  frontend_deployment_pipeline:
    name: frontend_deployment_pipeline
    needs: backend_deployment_pipeline
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install frontend dependencies
        run: |
          cd client
          npm install

      - name: Create env file
        run: |
          touch .env
          echo REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} >> .env
      
      - name: Lint frontend
        run: |
          cd client
          npm run lint
      
      - name: Build frontend
        run: |
          cd client
          npm run build
      
      - name: E2E tests for frontend
        if: ${{ github.event_name == 'push' && ! contains(toJson(github.event.head_commit.message), '#skip-e2e') }}
        run: |
          cd server
          npm run dev
          cd ..
          cd e2e-tests
          npm install
          npx playwright install --with-deps
          npm run test
      
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && ! contains(toJson(github.event.head_commit.message), '#skip-deploy') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}